### 获取用户列表
POST http://127.0.0.1:33001/api/user/getUserList
Content-Type: application/json



### 获取用户详细信息
POST http://127.0.0.1:33001/api/user/getUserInfo
Content-Type: application/json

{
    "userId": "23209010001"
}
